drop table if exists bookmarks;

create table bookmarks (
  id INTEGER primary key generated by default as identity,
  title text not null,
  url VARCHAR(2083) not null,
  description text,
  rating numeric not null
);

insert into bookmarks (title, url, description, rating)
values
  ('Amazon', 'https://www.amazon.com/', 'Buy literally anything', 4),
  ('Facebook', 'https://www.facebook.com/', 'Book of faces', 3),
  ('Google', 'https://www.google.com/', null, 5),
  ('Thinkful', 'https://www.thinkful.com/', 'Learn to code', 5),
  ('Github', 'https://github.com/', null, 4),
  ('LinkedIn', 'https://www.linkedin.com/', 'Social network for your professional network', 4),
  ('YouTube', 'https://www.youtube.com/', 'Not just cat videos', 3),
  ('Pandora', 'https://www.pandora.com/', 'Best online radio', 5),
  ('Twitter', 'https://twitter.com/', 'Look at all the opinions', 2),
  ('Steam', 'https://store.steampowered.com/', null, 5);
  